archives:
    -
        name_template: "{{ .Os }}_{{ .Arch }}"
        goarch:
            - 386
            - amd64
            - arm
            - arm64
        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - netbsd
            - solaris
        format: zip
        files:
            - none*
